### PR TITLE
Updated Django Docs Link

### PR DESCRIPTION
**Pull request by kailashchoudhary11**
Updated the Reference Links in Documentation to Point to Django 4.1

### CODE REVIEW

**Comment by kailashchoudhary11** [comment]
@Sibyx  Please Review!

**Comment by Sibyx** [comment]
Hello @kailashchoudhary11, first of all: thank you for your contribution. I have few issues with the PR:

- it's a good practice to provide a PR description
- latest Django version is 4.1
- please fix all the links inside the project (also the docs/ folder)

**Review by Sibyx — CHANGES_REQUESTED** [review]
- rewrite links to django 4.1 (please check the validity)
- please fix all the links inside the project (also the docs/ folder)

**Comment by kailashchoudhary11** [comment]
Okay Sure!

**Comment by kailashchoudhary11** [comment]
@Sibyx Please Review!

**Review by Sibyx — APPROVED** [review]

**Pull request merged**
